/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import clases.ModelTablaReporteOrdenes;
import java.awt.Rectangle;
import java.awt.event.ItemEvent;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/**
 *
 * @author puntodeventa-jlat
 */
public class IReporteDeOrdenes extends javax.swing.JInternalFrame {

    /**
     * Creates new form IReporteDeOrdenes
     */
    ModelTablaReporteOrdenes mdlOrdenes;
    public IReporteDeOrdenes(JDesktopPane mainApp) {
        initComponents();
        Rectangle visibleRect = mainApp.getVisibleRect();       
        this.setSize(visibleRect.width-160, visibleRect.height); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dcFechaInicial = new com.toedter.calendar.JDateChooser();
        dcFechaFinal = new com.toedter.calendar.JDateChooser();
        txtNombreCliente = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        bntMostrar = new javax.swing.JButton();
        bntImprimir = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalIngresos = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Ordenes");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fecha Inicial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 12, 4);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Final:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 12, 4);
        jPanel3.add(jLabel2, gridBagConstraints);

        dcFechaInicial.setDateFormatString("dd/MM/yyyy");
        dcFechaInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dcFechaInicial.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 12, 4);
        jPanel3.add(dcFechaInicial, gridBagConstraints);

        dcFechaFinal.setDateFormatString("dd/MM/yyyy");
        dcFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dcFechaFinal.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 12, 8);
        jPanel3.add(dcFechaFinal, gridBagConstraints);

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreCliente.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 13, 8);
        jPanel3.add(txtNombreCliente, gridBagConstraints);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Buscar por Cliente");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 5, 13, 0);
        jPanel3.add(jRadioButton1, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        bntMostrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/report_magnify.png"))); // NOI18N
        bntMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMostrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 14, 14, 2);
        jPanel4.add(bntMostrar, gridBagConstraints);

        bntImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/printer.png"))); // NOI18N
        bntImprimir.setEnabled(false);
        bntImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntImprimirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 14, 2);
        jPanel4.add(bntImprimir, gridBagConstraints);

        bntCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/cancel.png"))); // NOI18N
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 14, 13);
        jPanel4.add(bntCancelar, gridBagConstraints);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        tblOrdenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblOrdenes);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Total de Ingresos");
        jPanel6.add(jLabel3);

        txtTotalIngresos.setEditable(false);
        txtTotalIngresos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalIngresos.setPreferredSize(new java.awt.Dimension(120, 23));
        jPanel6.add(txtTotalIngresos);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMostrarActionPerformed
        if(this.dcFechaInicial.getCalendar() == null || this.dcFechaFinal.getCalendar()==null)
        {
            JOptionPane.showMessageDialog(this, "Ingrese fecha inicial y fecha final", "Debe ingresar ambas fecha", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(this.dcFechaInicial.getCalendar().getTime().after(this.dcFechaFinal.getCalendar().getTime()))
        {
            JOptionPane.showMessageDialog(this, "Ingrese fecha final debe ser mayor de fecha de inicio", "Error rango de fechas no valido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nombreCliente = this.txtNombreCliente.getText().isEmpty()?null:this.txtNombreCliente.getText();
        mdlOrdenes = new ModelTablaReporteOrdenes(this.dcFechaInicial.getCalendar().getTime(),this.dcFechaFinal.getCalendar().getTime(),nombreCliente);
        if(mdlOrdenes.estVacio())
        {
            JOptionPane.showMessageDialog(this, "No existe ningun registro entre la fechas ingresadas", "Sin registro", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        this.bntImprimir.setEnabled(true);
        this.tblOrdenes.setModel(mdlOrdenes);
        //this.txtTotalIngresos.setText(""+mdlIngresos.getTotales());
    }//GEN-LAST:event_bntMostrarActionPerformed

    private void bntImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntImprimirActionPerformed
        if(mdlOrdenes == null )
        {
            JOptionPane.showMessageDialog(this, "No se puede imprimir una tabla vacia", "Tabla sin registros", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        JFileChooser seleccionarDirecctorio = new JFileChooser();
        int grabado = seleccionarDirecctorio.showSaveDialog(null);
        String ruta = "";
        if(grabado == JFileChooser.APPROVE_OPTION)
        {
            ruta = seleccionarDirecctorio.getSelectedFile().getAbsolutePath()+".xls";

            File archivo = new File(ruta);
            try {
                DataOutputStream out = new DataOutputStream(new FileOutputStream(archivo));
                WritableWorkbook w = Workbook.createWorkbook(out);
                WritableSheet s = w.createSheet("Reporte de Pagos", 0);

                for (int i = 0; i < tblOrdenes.getRowCount(); i++) {
                    for (int j = 0; j < tblOrdenes.getColumnCount(); j++) {
                        Object objeto = tblOrdenes.getValueAt(i, j);
                        s.addCell(new Label(j,i, String.valueOf(objeto)));
                    }
                }
                w.write();
                w.close();
                out.close();
                JOptionPane.showMessageDialog(this, "Registros exportados correctamente\n"
                    + "se creo el archivo "+ruta, "Tabla sin registros", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }

    }//GEN-LAST:event_bntImprimirActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        this.dcFechaInicial.setCalendar(null);
        this.dcFechaFinal.setCalendar(null);
        this.bntImprimir.setEnabled(false);
        if(mdlOrdenes != null)
        {
            if(!mdlOrdenes.estVacio())
            {
                mdlOrdenes.limpiar();
            }
            mdlOrdenes = null;
        }
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        this.txtNombreCliente.setEditable(this.jRadioButton1.isSelected());
        if(evt.getStateChange() == ItemEvent.DESELECTED)
        {
            this.txtNombreCliente.setText("");
        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntImprimir;
    private javax.swing.JButton bntMostrar;
    private com.toedter.calendar.JDateChooser dcFechaFinal;
    private com.toedter.calendar.JDateChooser dcFechaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrdenes;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTotalIngresos;
    // End of variables declaration//GEN-END:variables
}
