package ventanas;

import java.awt.BorderLayout;
import java.awt.Rectangle;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import paneles.PnlReporteIngresos;

/**
 *
 * @author puntodeventa-jlat
 */
public class IReporteIngresos extends javax.swing.JInternalFrame {

    /**
     * Creates new form IReporteIngresos
     */
    public IReporteIngresos(JDesktopPane mainApp) {
        initComponents();
        Rectangle visibleRect = mainApp.getVisibleRect();       
        this.setSize(visibleRect.width-160, visibleRect.height);        
        PnlReporteIngresos pvc = new PnlReporteIngresos();
        this.getContentPane().add(pvc, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Ingresos");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
