/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles;

import clases.Pago;
import java.awt.Component;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author puntodeventa-jlat
 */
public class PnlImprimirPago extends javax.swing.JPanel implements Printable{

    /**
     * Creates new form PnlImprimirPago
     */
    private boolean procesoOk = false;
    private JOptionPane op;
    private Pago pago;
    public PnlImprimirPago(Pago pago) {
        initComponents();
        this.pago = pago;
        this.blNroFolio.setText(""+pago.getClvFolio());
        this.lbNombre.setText(pago.getNroCuenta().getNombre());
        this.lbDireccion.setText(pago.getNroCuenta().getDireccion());
        this.lbColonia.setText(pago.getNroCuenta().getColonia());
        this.lbMunicipio.setText(pago.getNroCuenta().getMunicipio());
        this.lbTelefono.setText(pago.getNroCuenta().getTelefono());
        this.lbRfc.setText(pago.getNroCuenta().getRfc());
        
        this.lbFechaCubierta.setText(pago.getFormatearFecha(pago.getFechaCubierta(), "dd/MM/yyyy"));
        this.lbMesesTranscurridos.setText(pago.getMesesTranscurridos()+"");
        this.lbFechaAPagar.setText(pago.getFormatearFecha(pago.getFechaDePago(), "dd/MM/yyyy"));
        this.lbRezagos.setText(""+pago.getRezago());
        this.lbRecargos.setText(""+pago.getRecargo());
        this.lbSubtotal.setText(""+pago.getPagoCalculado());
        this.lbTotal.setText(""+pago.getTotal());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        blNroFolio = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbColonia = new javax.swing.JLabel();
        lbMunicipio = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbRfc = new javax.swing.JLabel();
        lbFechaCubierta = new javax.swing.JLabel();
        lbMesesTranscurridos = new javax.swing.JLabel();
        lbFechaAPagar = new javax.swing.JLabel();
        lbRezagos = new javax.swing.JLabel();
        lbRecargos = new javax.swing.JLabel();
        lbSubtotal = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Comision de Agua Potable, Alcantarillado y Saneamiento ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Folio Nro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Datos del Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 7, 0);
        add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Direccion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Colonia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Municipio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Telefono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("RFC:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Datos del Pago");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 4, 0);
        add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Fecha Cubierta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
        add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Meses Transcurridos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Fecha a Pagar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Rezagos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Recargos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("SubTotal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        add(jLabel17, gridBagConstraints);

        blNroFolio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(13, 11, 0, 42);
        add(blNroFolio, gridBagConstraints);

        lbNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 11, 0, 42);
        add(lbNombre, gridBagConstraints);

        lbDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbDireccion, gridBagConstraints);

        lbColonia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbColonia, gridBagConstraints);

        lbMunicipio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbMunicipio, gridBagConstraints);

        lbTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbTelefono, gridBagConstraints);

        lbRfc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbRfc, gridBagConstraints);

        lbFechaCubierta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 0, 42);
        add(lbFechaCubierta, gridBagConstraints);

        lbMesesTranscurridos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMesesTranscurridos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbMesesTranscurridos, gridBagConstraints);

        lbFechaAPagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbFechaAPagar, gridBagConstraints);

        lbRezagos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbRezagos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbRezagos, gridBagConstraints);

        lbRecargos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbRecargos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbRecargos, gridBagConstraints);

        lbSubtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbSubtotal, gridBagConstraints);

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 42);
        add(lbTotal, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/printer.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 8, 0);
        add(jButton1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/cancel.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 9, 8, 0);
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getOptionPane();
        try{
    try
    {
      PrinterJob job = PrinterJob.getPrinterJob();
      job.setPrintable(this);
       if(job.printDialog())
       {
          job.print(); 
          procesoOk = true;
          op.setValue(1);
       }
        
      
    }
    catch (PrinterException ex)
    {
      JOptionPane.showMessageDialog( null, "NO EXISTEN IMPRESORAS INSTALADAS", "ERROR DE IMPRESION", JOptionPane.ERROR_MESSAGE);
    }
 }
 catch(Exception ex)
        {
            JOptionPane.showMessageDialog( null, "NO EXISTEN IMPRESORAS INSTALADAS", "ERROR DE IMPRESION", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getOptionPane();
        op.setValue(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public boolean getProcesoOk()
    {
        return this.procesoOk;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blNroFolio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbColonia;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbFechaAPagar;
    private javax.swing.JLabel lbFechaCubierta;
    private javax.swing.JLabel lbMesesTranscurridos;
    private javax.swing.JLabel lbMunicipio;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbRecargos;
    private javax.swing.JLabel lbRezagos;
    private javax.swing.JLabel lbRfc;
    private javax.swing.JLabel lbSubtotal;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
    try
    {
        if (pageIndex > 0)
        { 
          return NO_SUCH_PAGE;
        }
      Graphics2D g2d = (Graphics2D)graphics;
      g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());  
      FontMetrics fm = g2d.getFontMetrics();
      int anchoMayor = fm.stringWidth("Meses Transcurridos: ");      
      int posx = 50;
      int posy = 50;
      g2d.drawString("Comision de Agua Potable, Alcantarillado y Saneamiento ", posx, 40);
      g2d.drawLine(0, posy, (int)pageFormat.getImageableWidth(), posy);
      posy +=15;
      g2d.drawString("Datos del Cliente", posx, posy);
      g2d.drawLine(0, posy+3, (int)pageFormat.getImageableWidth(), posy+3);
      posy +=15;
      g2d.drawString("Nombre: "+pago.getNroCuenta().getNombre(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Nombre: ")), posy);
      posy +=15;
      g2d.drawString("Direccion: "+pago.getNroCuenta().getDireccion(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Direccion: ")), posy);
      posy +=15;
      g2d.drawString("Colonia: "+pago.getNroCuenta().getColonia(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Colonia: ")), posy);
      posy +=15;
      g2d.drawString("Municipio: "+pago.getNroCuenta().getMunicipio(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Municipio: ")), posy);
      posy +=15;
      g2d.drawString("Telefono: "+pago.getNroCuenta().getTelefono(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Telefono: ")), posy);
      posy +=15;
      g2d.drawString("RFC: "+pago.getNroCuenta().getRfc(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("RFC: ")), posy);
      g2d.drawLine(0, posy+3, (int)pageFormat.getImageableWidth(), posy+3);
      posy +=15;
      g2d.drawString("Datos del Pago", posx, posy);
      g2d.drawLine(0, posy+3, (int)pageFormat.getImageableWidth(), posy+3);
      posy +=15;
      g2d.drawString("Fecha Cubierta: "+pago.getFormatearFecha(pago.getFechaCubierta(), "dd/MM/yyyy"), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Fecha Cubierta: ")), posy);
      posy +=15;
      g2d.drawString("Meses Transcurridos: "+pago.getMesesTranscurridos(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Meses Transcurridos: ")), posy);
      posy +=15;
      g2d.drawString("Fecha a Pagar: "+pago.getFormatearFecha(pago.getFechaDePago(), "dd/MM/yyyy"), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Fecha a Pagar: ")), posy);
      posy +=15;
      g2d.drawString("Rezagos: "+pago.getRezago(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Rezagos: ")), posy);
      posy +=15;
      g2d.drawString("Recargos: "+pago.getRecargo(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Recargos: ")), posy);
      posy +=15;
      g2d.drawString("Subtotal: "+pago.getPagoCalculado(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Subtotal: ")), posy);
      posy +=15;
      g2d.drawString("Total: "+pago.getTotal(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Total: ")), posy);
      
           
      //this.printAll(graphics);
      return PAGE_EXISTS;
    }
    catch(Exception ex)
        {
            JOptionPane.showMessageDialog( null, "NO HAY OBJETOS A IMPRIMIR", "ERROR DEIMPRESION", JOptionPane.ERROR_MESSAGE);
        }
    return PAGE_EXISTS;
    }
    
    public int getDiferenciaAncho(int mayor, int menor)
    {
        return mayor-menor;
    }
     
    JLabel getLabelEscondido() {
        JLabel lab = new JLabel();
        lab.setVisible(false);
        return lab;
    }
    
     private void getOptionPane()
    {
        if(op != null)
        {
            return;
        }
        Component pdr =this.getParent(); 
        while(pdr.getParent() != null)
        {
            if(pdr instanceof JOptionPane)
            {
                op = (JOptionPane)pdr;
                break;
            }            
            pdr = pdr.getParent();
        }
    }
}
