/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles;

import clases.Orden;
import java.awt.Component;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author puntodeventa-jlat
 */
public class PnlImprimirOrden extends javax.swing.JPanel implements Printable{

    /**
     * Creates new form PnlImprimirOrden
     */
    private Orden orden;
    private boolean procesoOk = false;
    private JOptionPane op;
    public PnlImprimirOrden(Orden orden) {
        initComponents();
        this.orden = orden;
        this.lbNroCuenta.setText(""+this.orden.getCliente().getNumeroCuenta());
        this.lbNombre.setText(this.orden.getCliente().getNombre());
        this.lbDireccion.setText(this.orden.getCliente().getDireccion());
        this.lbColonia.setText(this.orden.getCliente().getColonia());
        this.lbMunicipio.setText(this.orden.getCliente().getMunicipio());
        this.lbTelefono.setText(this.orden.getCliente().getTelefono());
        this.lbRfc.setText(this.orden.getCliente().getRfc());
        this.lbInspector.setText(this.orden.getInspector());
        this.lbTipoOrden.setText(this.orden.getTipo());
        this.lbMotivo.setText(this.orden.getMotivoCorte());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbNroCuenta = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbColonia = new javax.swing.JLabel();
        lbMunicipio = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbRfc = new javax.swing.JLabel();
        lbInspector = new javax.swing.JLabel();
        lbTipoOrden = new javax.swing.JLabel();
        lbMotivo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Comiision de Agua Potable, Alcantarillado y Saneamiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 9, 13);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nro de Cuenta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Direccion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Colonia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Municipio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Telefono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("RFC:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Inspector:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tipo Orden:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Motivo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 2, 0);
        add(jLabel11, gridBagConstraints);

        lbNroCuenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbNroCuenta, gridBagConstraints);

        lbNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbNombre, gridBagConstraints);

        lbDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbDireccion, gridBagConstraints);

        lbColonia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbColonia, gridBagConstraints);

        lbMunicipio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbMunicipio, gridBagConstraints);

        lbTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbTelefono, gridBagConstraints);

        lbRfc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbRfc, gridBagConstraints);

        lbInspector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbInspector, gridBagConstraints);

        lbTipoOrden.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbTipoOrden, gridBagConstraints);

        lbMotivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 2, 0);
        add(lbMotivo, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/printer.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 12, 6);
        add(jButton1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/cross.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 12, 0);
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         getOptionPane();
         op.setValue(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getOptionPane();
        try{
    try
    {
      PrinterJob job = PrinterJob.getPrinterJob();
      job.setPrintable(this);
       if(job.printDialog())
       {
          job.print(); 
          procesoOk = true;
          op.setValue(1);
       }
        
      
    }
    catch (PrinterException ex)
    {
      JOptionPane.showMessageDialog( null, "NO EXISTEN IMPRESORAS INSTALADAS", "ERROR DE IMPRESION", JOptionPane.ERROR_MESSAGE);
    }
 }
 catch(Exception ex)
        {
            JOptionPane.showMessageDialog( null, "NO EXISTEN IMPRESORAS INSTALADAS", "ERROR DE IMPRESION", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean getProcesoOk()
    {
        return this.procesoOk;
    }
    
    public int getDiferenciaAncho(int mayor, int menor)
    {
        return mayor-menor;
    }
     
    JLabel getLabelEscondido() {
        JLabel lab = new JLabel();
        lab.setVisible(false);
        return lab;
    }
    
     private void getOptionPane()
    {
        if(op != null)
        {
            return;
        }
        Component pdr =this.getParent(); 
        while(pdr.getParent() != null)
        {
            if(pdr instanceof JOptionPane)
            {
                op = (JOptionPane)pdr;
                break;
            }            
            pdr = pdr.getParent();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbColonia;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbInspector;
    private javax.swing.JLabel lbMotivo;
    private javax.swing.JLabel lbMunicipio;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNroCuenta;
    private javax.swing.JLabel lbRfc;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTipoOrden;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        try
    {
        if (pageIndex > 0)
        { 
          return NO_SUCH_PAGE;
        }
      Graphics2D g2d = (Graphics2D)graphics;
      g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());  
      FontMetrics fm = g2d.getFontMetrics();
      int anchoMayor = fm.stringWidth("Nro de Cuenta: ");      
      int posx = 50;
      int posy = 50;
      g2d.drawString("Comision de Agua Potable, Alcantarillado y Saneamiento ", posx, 40);
      g2d.drawLine(0, posy, (int)pageFormat.getImageableWidth(), posy);
      posy +=15;
      g2d.drawString("Datos del Cliente", posx, posy);
      g2d.drawLine(0, posy+3, (int)pageFormat.getImageableWidth(), posy+3);
      posy +=15;
      g2d.drawString("Nombre: "+this.orden.getCliente().getNombre(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Nombre: ")), posy);
      posy +=15;
      g2d.drawString("Direccion: "+this.orden.getCliente().getDireccion(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Direccion: ")), posy);
      posy +=15;
      g2d.drawString("Colonia: "+this.orden.getCliente().getColonia(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Colonia: ")), posy);
      posy +=15;
      g2d.drawString("Municipio: "+this.orden.getCliente().getMunicipio(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Municipio: ")), posy);
      posy +=15;
      g2d.drawString("Telefono: "+this.orden.getCliente().getTelefono(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Telefono: ")), posy);
      posy +=15;
      g2d.drawString("RFC: "+this.orden.getCliente().getRfc(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("RFC: ")), posy);
            posy +=15;      
      g2d.drawString("Inspector: "+this.orden.getInspector(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Inspector: ")), posy);
      posy +=15;
      g2d.drawString("Tipo Orden: "+this.orden.getTipo(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Tipo Orden: ")), posy);
      posy +=15;
      g2d.drawLine(0, posy+3, (int)pageFormat.getImageableWidth(), posy+3);
      g2d.drawString("Motivo", posx, posy);
      g2d.drawLine(0, posy+3, (int)pageFormat.getImageableWidth(), posy+3);
      posy +=15;
      g2d.drawString("Motivo: "+this.orden.getMotivoCorte(), posx+getDiferenciaAncho(anchoMayor,fm.stringWidth("Motivo: ")), posy);
     
     
           
      //this.printAll(graphics);
      return PAGE_EXISTS;
    }
    catch(Exception ex)
        {
            JOptionPane.showMessageDialog( null, "NO HAY OBJETOS A IMPRIMIR", "ERROR DEIMPRESION", JOptionPane.ERROR_MESSAGE);
        }
    return PAGE_EXISTS;
    }
}
