/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles;

import clases.Cliente;
import java.awt.Component;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class PnlNuevoCliente extends javax.swing.JPanel {

    /**
     * Creates new form PnlNuevoCliente
     */
    
    private Cliente nuevoCliente;
    private boolean esClienteNuevo = true;
    private boolean procesoOk = false;
    private JOptionPane op;
    public PnlNuevoCliente() {
        initComponents();
        nuevoCliente = new Cliente();
        this.lbShow.setVisible(false);
    }

    public PnlNuevoCliente(Cliente nuevoCliente) {
        initComponents();
        this.nuevoCliente = nuevoCliente;
        esClienteNuevo = false;
        this.lbShow.setVisible(false);
        this.bntCancelar.setVisible(false);
        this.txtNombre.setText(nuevoCliente.getNombre());
        this.txtDireccion.setText(nuevoCliente.getDireccion());
        this.txtTelefono.setText(nuevoCliente.getTelefono());
        this.txtRfc.setText(nuevoCliente.getRfc());
        this.txtColonia.setText(nuevoCliente.getColonia());
        this.txtComunidad.setText(nuevoCliente.getComunidad());
        this.txtMunicipio.setText(nuevoCliente.getMunicipio());
        this.txtCodigoPostal.setText(nuevoCliente.getCodigoPostal());
        this.cbTarifas.setSelectedItem(nuevoCliente.getTarifa());
        this.dcFechaRegistro.setDate(nuevoCliente.getFechaRegistro());
    }
    
    public JLabel getLabelEscondido()
    {
        return this.lbShow;
    }
    
     public boolean IsProcesoOk()
    {
        return procesoOk;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtComunidad = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        cbTarifas = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bntGuardar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        bntCerrar = new javax.swing.JButton();
        lbShow = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fecha de Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(18, 9, 5, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 9, 5, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Direccion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 9, 5, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Telefono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 9, 5, 10);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("RFC:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 6);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Colonia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 9, 5, 10);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Comunidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 9, 5, 10);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Municipio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 9, 5, 10);
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cod. Postal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 9, 14, 10);
        jPanel1.add(jLabel9, gridBagConstraints);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(280, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 15);
        jPanel1.add(txtNombre, gridBagConstraints);

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.setPreferredSize(new java.awt.Dimension(280, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 15);
        jPanel1.add(txtDireccion, gridBagConstraints);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefono.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 0);
        jPanel1.add(txtTelefono, gridBagConstraints);

        txtRfc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRfc.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 15);
        jPanel1.add(txtRfc, gridBagConstraints);

        txtColonia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtColonia.setPreferredSize(new java.awt.Dimension(280, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 15);
        jPanel1.add(txtColonia, gridBagConstraints);

        txtComunidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtComunidad.setPreferredSize(new java.awt.Dimension(280, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 15);
        jPanel1.add(txtComunidad, gridBagConstraints);

        txtMunicipio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMunicipio.setPreferredSize(new java.awt.Dimension(140, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 0);
        jPanel1.add(txtMunicipio, gridBagConstraints);

        txtCodigoPostal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigoPostal.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 14, 0);
        jPanel1.add(txtCodigoPostal, gridBagConstraints);

        cbTarifas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTarifas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domestico", "Comercial", "Industrial", "Publico", "Insen", "Baldio", "Especial" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 14, 15);
        jPanel1.add(cbTarifas, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tarifa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 14, 6);
        jPanel1.add(jLabel10, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridBagLayout());

        bntGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntGuardar.setText("Guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        jPanel2.add(bntGuardar, gridBagConstraints);

        bntCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        jPanel2.add(bntCancelar, gridBagConstraints);

        bntCerrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntCerrar.setText("Cerrar");
        bntCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCerrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        jPanel2.add(bntCerrar, gridBagConstraints);
        jPanel2.add(lbShow, new java.awt.GridBagConstraints());

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        
        if(this.txtNombre.getText().isEmpty())
        {
            JOptionPane.showInternalMessageDialog(this, "Debe ingresar el nombre del Cliente"
                    , "Ingrese un nombre", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(this.txtDireccion.getText().isEmpty())
        {
            JOptionPane.showInternalMessageDialog(this, "Debe ingresar la direccion del Cliente"
                    , "Ingrese una Direccion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int procesoCorrecto = 0;
        
        nuevoCliente.setNombre(this.txtNombre.getText());
        nuevoCliente.setDireccion(this.txtDireccion.getText());
        nuevoCliente.setTelefono(this.txtTelefono.getText());
        nuevoCliente.setRfc(this.txtRfc.getText());
        nuevoCliente.setColonia(this.txtColonia.getText());
        nuevoCliente.setComunidad(this.txtComunidad.getText());
        nuevoCliente.setMunicipio(this.txtMunicipio.getText());
        nuevoCliente.setCodigoPostal(this.txtCodigoPostal.getText());
        nuevoCliente.setTarifa(this.cbTarifas.getSelectedItem().toString());
        nuevoCliente.setFechaRegistro(this.dcFechaRegistro.getCalendar().getTime());
     
        if(this.esClienteNuevo)
        {
            procesoCorrecto = nuevoCliente.grabar();
            
        }else{
           procesoCorrecto = nuevoCliente.actualizar();
        }
        
        if(procesoCorrecto != 0 && this.esClienteNuevo)
        { 
            this.procesoOk = true;
            int confirmacion = JOptionPane.showConfirmDialog(null, "Datos Guardado Correctamente.\n"
                    + "¿Desea Agregar otro usuario?",  "¿Desea continuar?",  JOptionPane.YES_NO_CANCEL_OPTION);
            if(confirmacion == JOptionPane.OK_OPTION)
            {
                reiniciarCampos();               
            }else
            {
                getOptionPane();
                op.setValue(1);
            }
            
        }else if(procesoCorrecto != 0 && !this.esClienteNuevo){
            this.procesoOk = true;
            JOptionPane.showInternalMessageDialog(this, "Usuario Actualizdo Correctamente"
                    , "Actualizacion Correcta.", JOptionPane.INFORMATION_MESSAGE); 
//             getOptionPane();
//             op.setValue(1);
        }else{
            JOptionPane.showInternalMessageDialog(this, "No fue posible Guardar los datos."
                    , "Error!!", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_bntGuardarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
       reiniciarCampos();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void bntCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCerrarActionPerformed
       getOptionPane();
       op.setValue(1);
    }//GEN-LAST:event_bntCerrarActionPerformed


    
    private void getOptionPane()
    {
        if(op != null)
        {
            return;
        }
        Component pdr =this.getParent(); 
        while(pdr.getParent() != null)
        {
            if(pdr instanceof JOptionPane)
            {
                op = (JOptionPane)pdr;
                break;
            }            
            pdr = pdr.getParent();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntCerrar;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JComboBox cbTarifas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbShow;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtComunidad;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void reiniciarCampos() {
       this.txtNombre.setText("");
       this.txtDireccion.setText("");
       this.txtTelefono.setText("");
       this.txtRfc.setText("");
       this.txtColonia.setText("");
       this.txtComunidad.setText("");
       this.txtMunicipio.setText("");
       this.txtCodigoPostal.setText("");
       this.cbTarifas.setSelectedIndex(0);
       this.dcFechaRegistro.setCalendar(null);
    }
}
