package paneles;

import clases.ModelTablaReporteIngresos;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/**
 *
 * @author puntodeventa-jlat
 */
public class PnlReporteIngresos extends javax.swing.JPanel {

    /**
     * Creates new form PnlReporteIngresos
     */
    ModelTablaReporteIngresos mdlIngresos = null;
    public PnlReporteIngresos() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dcFechaInicial = new com.toedter.calendar.JDateChooser();
        dcFechaFinal = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        bntMostrar = new javax.swing.JButton();
        bntImprimir = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngresos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalIngresos = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fecha Inicial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 12, 4);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Final:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 12, 4);
        jPanel2.add(jLabel2, gridBagConstraints);

        dcFechaInicial.setDateFormatString("dd/MM/yyyy");
        dcFechaInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dcFechaInicial.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 12, 4);
        jPanel2.add(dcFechaInicial, gridBagConstraints);

        dcFechaFinal.setDateFormatString("dd/MM/yyyy");
        dcFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dcFechaFinal.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 12, 8);
        jPanel2.add(dcFechaFinal, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        bntMostrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/report_magnify.png"))); // NOI18N
        bntMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMostrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 14, 14, 2);
        jPanel3.add(bntMostrar, gridBagConstraints);

        bntImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/printer.png"))); // NOI18N
        bntImprimir.setEnabled(false);
        bntImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntImprimirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 14, 2);
        jPanel3.add(bntImprimir, gridBagConstraints);

        bntCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/cancel.png"))); // NOI18N
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 14, 13);
        jPanel3.add(bntCancelar, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        tblIngresos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblIngresos);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Total de Ingresos");
        jPanel5.add(jLabel3);

        txtTotalIngresos.setEditable(false);
        txtTotalIngresos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalIngresos.setPreferredSize(new java.awt.Dimension(120, 23));
        jPanel5.add(txtTotalIngresos);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bntMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMostrarActionPerformed
       if(this.dcFechaInicial.getCalendar() == null || this.dcFechaFinal.getCalendar()==null)
       {
           JOptionPane.showMessageDialog(this, "Ingrese fecha inicial y fecha final", "Debe ingresar ambas fecha", JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       if(this.dcFechaInicial.getCalendar().getTime().after(this.dcFechaFinal.getCalendar().getTime()))
       {
           JOptionPane.showMessageDialog(this, "Ingrese fecha final debe ser mayor de fecha de inicio", "Error rango de fechas no valido", JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       mdlIngresos = new ModelTablaReporteIngresos(this.dcFechaInicial.getCalendar().getTime(),this.dcFechaFinal.getCalendar().getTime());
       if(mdlIngresos.estVacio())
       {           
           JOptionPane.showMessageDialog(this, "No existe ningun registro entre la fechas ingresadas", "Sin registro", JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       this.bntImprimir.setEnabled(true);
       this.tblIngresos.setModel(mdlIngresos);
       this.txtTotalIngresos.setText(""+mdlIngresos.getTotales());
    }//GEN-LAST:event_bntMostrarActionPerformed

    private void bntImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntImprimirActionPerformed
        if(mdlIngresos == null )
        {
             JOptionPane.showMessageDialog(this, "No se puede imprimir una tabla vacia", "Tabla sin registros", JOptionPane.INFORMATION_MESSAGE);
             return;
        }
        JFileChooser seleccionarDirecctorio = new JFileChooser();        
        int grabado = seleccionarDirecctorio.showSaveDialog(null); 
        String ruta = "";
        if(grabado == JFileChooser.APPROVE_OPTION)
        {   
            ruta = seleccionarDirecctorio.getSelectedFile().getAbsolutePath()+".xls";
            
            File archivo = new File(ruta);
            try {
                DataOutputStream out = new DataOutputStream(new FileOutputStream(archivo));
                WritableWorkbook w = Workbook.createWorkbook(out);
                WritableSheet s = w.createSheet("Reporte de Pagos", 0);

                for (int i = 0; i < tblIngresos.getRowCount(); i++) {
                    for (int j = 0; j < tblIngresos.getColumnCount(); j++) {
                        Object objeto = tblIngresos.getValueAt(i, j);
                        s.addCell(new Label(j,i, String.valueOf(objeto)));
                    }
                }
                w.write();
                w.close();
                out.close(); 
                JOptionPane.showMessageDialog(this, "Registros exportados correctamente\n"
                        + "se creo el archivo "+ruta, "Tabla sin registros", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
               ex.printStackTrace();
            }
            
        }
        
    }//GEN-LAST:event_bntImprimirActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        this.dcFechaInicial.setCalendar(null);
        this.dcFechaFinal.setCalendar(null);
        this.bntImprimir.setEnabled(false);
        if(mdlIngresos != null)
        {
            if(!mdlIngresos.estVacio())
            {
                mdlIngresos.limpiar();                
            }
            mdlIngresos = null;
        }
    }//GEN-LAST:event_bntCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntImprimir;
    private javax.swing.JButton bntMostrar;
    private com.toedter.calendar.JDateChooser dcFechaFinal;
    private com.toedter.calendar.JDateChooser dcFechaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIngresos;
    private javax.swing.JTextField txtTotalIngresos;
    // End of variables declaration//GEN-END:variables

    public JLabel getLabelEscondido() {
        return new JLabel();
    }
}
