package paneles;

import clases.Usuario;
import java.awt.Component;
import java.awt.event.ItemEvent;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author puntodeventa-jlat
 */
public class PnlUsuarioNuevo extends javax.swing.JPanel {

    /**
     * Creates new form PnlUsuarioNuevo
     */
    private Usuario nuevoUsuario;
    private boolean esUsuarioNuevo = true;
    private boolean procesoOk = false;
    JOptionPane op;
    public PnlUsuarioNuevo() {
        initComponents();
        nuevoUsuario = new Usuario();
        this.lbShow.setVisible(false);
    }
    
    public PnlUsuarioNuevo(Usuario modificarUsuario) {
        initComponents();
        esUsuarioNuevo = false;
        nuevoUsuario = modificarUsuario;
        this.bntCancelar.setVisible(false);
        this.lbShow.setVisible(false);
        this.txtUsuario.setText(nuevoUsuario.getUsuario());
        this.txtPassword.setText(nuevoUsuario.getPasswd());
        this.cbArchivo.setSelected(nuevoUsuario.isArchivo());
        this.cbIniciarSesion.setSelected(nuevoUsuario.isIniciarSesion());
        this.cbCerrarSesion.setSelected(nuevoUsuario.isCerrarSesion());
        this.cbRegistroUsuarios.setSelected(nuevoUsuario.isRegistroDeUsuario());
        this.cbSalirAplicacion.setSelected(nuevoUsuario.isSalirDeAplicacion());
        this.cbClientes.setSelected(nuevoUsuario.isClientes());
        this.cbRegistroClientes.setSelected(nuevoUsuario.isRegistroDeClientes());
        this.cbPagos.setSelected(nuevoUsuario.isPagos());
        this.cbRegistroPagosPorClientes.setSelected(nuevoUsuario.isRegistrosDePagos());
        this.cbEmisionDeOrdenes.setSelected(nuevoUsuario.isEmisionesDeOrdenes());
        this.cbReportes.setSelected(nuevoUsuario.isReportes());
        this.cbReporteIngresos.setSelected(nuevoUsuario.isReporteDeIngresos());
        this.cbReportePagosClientes.setSelected(nuevoUsuario.isReporteDePagos());
        this.cbReporteOrdenesEnviadas.setSelected(nuevoUsuario.isReporteDeOrdenes());
        this.cbHerramientas.setSelected(nuevoUsuario.isHerramientas());
        this.cbRespaldarBd.setSelected(nuevoUsuario.isRespladarBd());
        this.cbRestaurarBd.setSelected(nuevoUsuario.isRestaurarBd());
        this.cbAyuda.setSelected(nuevoUsuario.isAyuda());
        this.cbAcercaDe.setSelected(nuevoUsuario.isAcercade());
        
    }
    
    
    public void activarPrivilegios(JPanel grupoBotones,boolean option)
    {
        Component[] components = grupoBotones.getComponents();
        for(Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox tmpCb = (JCheckBox)component;
                tmpCb.setSelected(option);
            }
        }        
    }
    
    public JLabel getLabelEscondido()
    {
        return this.lbShow;
    }
    
    public void reiniciarCampos()
    {
        this.cbArchivo.setSelected(false);
        this.activarPrivilegios(this.pnlArchivo, false);
        this.cbClientes.setSelected(false);
        this.activarPrivilegios(this.pnlClientes, false);
        this.cbClientes.setSelected(false);
        this.activarPrivilegios(this.pnlPagos, false);
        this.cbPagos.setSelected(false);
        this.activarPrivilegios(this.pnlReportes, false); 
        this.cbReportes.setSelected(false);
        this.activarPrivilegios(this.pnlHerramientas, false);
        this.cbHerramientas.setSelected(false);
        this.activarPrivilegios(this.pnlAyuda, false);
        this.cbAyuda.setSelected(false);
        this.txtUsuario.setText("");
        this.txtPassword.setText("");
    }
    
    public boolean IsProcesoOk()
    {
        return procesoOk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlArchivo = new javax.swing.JPanel();
        cbIniciarSesion = new javax.swing.JCheckBox();
        cbCerrarSesion = new javax.swing.JCheckBox();
        cbRegistroUsuarios = new javax.swing.JCheckBox();
        cbSalirAplicacion = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        cbArchivo = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        cbClientes = new javax.swing.JCheckBox();
        pnlClientes = new javax.swing.JPanel();
        cbRegistroClientes = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        cbPagos = new javax.swing.JCheckBox();
        pnlPagos = new javax.swing.JPanel();
        cbRegistroPagosPorClientes = new javax.swing.JCheckBox();
        cbEmisionDeOrdenes = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        cbReportes = new javax.swing.JCheckBox();
        pnlReportes = new javax.swing.JPanel();
        cbReporteIngresos = new javax.swing.JCheckBox();
        cbReportePagosClientes = new javax.swing.JCheckBox();
        cbReporteOrdenesEnviadas = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        cbHerramientas = new javax.swing.JCheckBox();
        pnlHerramientas = new javax.swing.JPanel();
        cbCalculadora = new javax.swing.JCheckBox();
        cbRespaldarBd = new javax.swing.JCheckBox();
        cbRestaurarBd = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        cbAyuda = new javax.swing.JCheckBox();
        pnlAyuda = new javax.swing.JPanel();
        cbActivarAyuda = new javax.swing.JCheckBox();
        cbAcercaDe = new javax.swing.JCheckBox();
        jPanel21 = new javax.swing.JPanel();
        bntGuardar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbShow = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 9, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 13, 0, 0);
        jPanel1.add(txtUsuario, gridBagConstraints);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 13, 9, 0);
        jPanel1.add(txtPassword, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Privilegios:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 18))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        pnlArchivo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlArchivo.setLayout(new java.awt.GridLayout(4, 0));

        cbIniciarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbIniciarSesion.setText("Iniciar Sesion");
        cbIniciarSesion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIniciarSesionItemStateChanged(evt);
            }
        });
        pnlArchivo.add(cbIniciarSesion);

        cbCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbCerrarSesion.setText("Cerrar Sesion");
        cbCerrarSesion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCerrarSesionItemStateChanged(evt);
            }
        });
        pnlArchivo.add(cbCerrarSesion);

        cbRegistroUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbRegistroUsuarios.setText("Registro de Usuarios");
        cbRegistroUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRegistroUsuariosItemStateChanged(evt);
            }
        });
        pnlArchivo.add(cbRegistroUsuarios);

        cbSalirAplicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSalirAplicacion.setText("Salir de la Aplicacion");
        cbSalirAplicacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSalirAplicacionItemStateChanged(evt);
            }
        });
        pnlArchivo.add(cbSalirAplicacion);

        jPanel3.add(pnlArchivo, java.awt.BorderLayout.CENTER);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        cbArchivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbArchivo.setText("Archivo");
        cbArchivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbArchivoItemStateChanged(evt);
            }
        });
        jPanel10.add(cbArchivo, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.GridBagLayout());

        cbClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbClientes.setText("Clientes");
        cbClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClientesItemStateChanged(evt);
            }
        });
        jPanel11.add(cbClientes, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        pnlClientes.setLayout(new java.awt.GridLayout(4, 0));

        cbRegistroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbRegistroClientes.setText("Registro de Clientes");
        cbRegistroClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRegistroClientesItemStateChanged(evt);
            }
        });
        pnlClientes.add(cbRegistroClientes);

        jPanel4.add(pnlClientes, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel13.setLayout(new java.awt.GridBagLayout());

        cbPagos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPagos.setText("Pagos");
        cbPagos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPagosItemStateChanged(evt);
            }
        });
        jPanel13.add(cbPagos, new java.awt.GridBagConstraints());

        jPanel5.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        pnlPagos.setLayout(new java.awt.GridLayout(4, 0));

        cbRegistroPagosPorClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbRegistroPagosPorClientes.setText("Registro de Pagos Por Clientes");
        cbRegistroPagosPorClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRegistroPagosPorClientesItemStateChanged(evt);
            }
        });
        pnlPagos.add(cbRegistroPagosPorClientes);

        cbEmisionDeOrdenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbEmisionDeOrdenes.setText("Emision de Ordenes (Corte/Reconexion)");
        cbEmisionDeOrdenes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEmisionDeOrdenesItemStateChanged(evt);
            }
        });
        pnlPagos.add(cbEmisionDeOrdenes);

        jPanel5.add(pnlPagos, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.GridBagLayout());

        cbReportes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbReportes.setText("Reportes");
        cbReportes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbReportesItemStateChanged(evt);
            }
        });
        jPanel15.add(cbReportes, new java.awt.GridBagConstraints());

        jPanel6.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        pnlReportes.setLayout(new java.awt.GridLayout(4, 0));

        cbReporteIngresos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbReporteIngresos.setText("Reporte de Ingresos");
        cbReporteIngresos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbReporteIngresosItemStateChanged(evt);
            }
        });
        pnlReportes.add(cbReporteIngresos);

        cbReportePagosClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbReportePagosClientes.setText("Reporte de Pagos Por Cliente");
        cbReportePagosClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbReportePagosClientesItemStateChanged(evt);
            }
        });
        pnlReportes.add(cbReportePagosClientes);

        cbReporteOrdenesEnviadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbReporteOrdenesEnviadas.setText("Reporte de Ordenes Enviadas");
        cbReporteOrdenesEnviadas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbReporteOrdenesEnviadasItemStateChanged(evt);
            }
        });
        pnlReportes.add(cbReporteOrdenesEnviadas);

        jPanel6.add(pnlReportes, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new java.awt.GridBagLayout());

        cbHerramientas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbHerramientas.setText("Herramientas");
        cbHerramientas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbHerramientasItemStateChanged(evt);
            }
        });
        jPanel17.add(cbHerramientas, new java.awt.GridBagConstraints());

        jPanel7.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        pnlHerramientas.setLayout(new java.awt.GridLayout(4, 0));

        cbCalculadora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbCalculadora.setText("Calculadora");
        cbCalculadora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCalculadoraItemStateChanged(evt);
            }
        });
        pnlHerramientas.add(cbCalculadora);

        cbRespaldarBd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbRespaldarBd.setText("Respaldar BD");
        cbRespaldarBd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRespaldarBdItemStateChanged(evt);
            }
        });
        pnlHerramientas.add(cbRespaldarBd);

        cbRestaurarBd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbRestaurarBd.setText("Restaurar BD");
        cbRestaurarBd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRestaurarBdItemStateChanged(evt);
            }
        });
        pnlHerramientas.add(cbRestaurarBd);

        jPanel7.add(pnlHerramientas, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.GridBagLayout());

        cbAyuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAyuda.setText("Ayuda");
        cbAyuda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAyudaItemStateChanged(evt);
            }
        });
        jPanel19.add(cbAyuda, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel19, java.awt.BorderLayout.PAGE_START);

        pnlAyuda.setLayout(new java.awt.GridLayout(4, 0));

        cbActivarAyuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbActivarAyuda.setText("Ayuda");
        cbActivarAyuda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbActivarAyudaItemStateChanged(evt);
            }
        });
        pnlAyuda.add(cbActivarAyuda);

        cbAcercaDe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAcercaDe.setText("Acerca De");
        cbAcercaDe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAcercaDeItemStateChanged(evt);
            }
        });
        pnlAyuda.add(cbAcercaDe);

        jPanel8.add(pnlAyuda, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel21.setLayout(new java.awt.GridBagLayout());

        bntGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntGuardar.setText("Guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });
        jPanel21.add(bntGuardar, new java.awt.GridBagConstraints());

        bntCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });
        jPanel21.add(bntCancelar, new java.awt.GridBagConstraints());

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton3, new java.awt.GridBagConstraints());
        jPanel21.add(lbShow, new java.awt.GridBagConstraints());

        add(jPanel21, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void cbArchivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbArchivoItemStateChanged
       boolean seleccion = evt.getStateChange() == ItemEvent.SELECTED;
       this.activarPrivilegios(this.pnlArchivo, seleccion);
       nuevoUsuario.setArchivo(seleccion);
       nuevoUsuario.setIniciarSesion(seleccion);
       nuevoUsuario.setCerrarSesion(seleccion);
       nuevoUsuario.setRegistroDeUsuario(seleccion);
       nuevoUsuario.setSalirDeAplicacion(seleccion);
    }//GEN-LAST:event_cbArchivoItemStateChanged

    private void cbClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClientesItemStateChanged
       boolean seleccion = evt.getStateChange() == ItemEvent.SELECTED;
       this.activarPrivilegios(this.pnlClientes, seleccion);
       nuevoUsuario.setClientes(seleccion);
       nuevoUsuario.setRegistroDeClientes(seleccion);
    }//GEN-LAST:event_cbClientesItemStateChanged

    private void cbPagosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPagosItemStateChanged
       boolean seleccion = evt.getStateChange() == ItemEvent.SELECTED;
       this.activarPrivilegios(this.pnlPagos, seleccion);
       nuevoUsuario.setPagos(seleccion);
       nuevoUsuario.setRegistrosDePagos(seleccion);
       nuevoUsuario.setEmisionesDeOrdenes(seleccion);
    }//GEN-LAST:event_cbPagosItemStateChanged

    private void cbReportesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbReportesItemStateChanged
       boolean seleccion = evt.getStateChange() == ItemEvent.SELECTED;
       this.activarPrivilegios(this.pnlReportes, seleccion);
       nuevoUsuario.setReportes(seleccion);
       nuevoUsuario.setReporteDeIngresos(seleccion);
       nuevoUsuario.setReporteDePagos(seleccion);
       nuevoUsuario.setReporteDeOrdenes(seleccion);
    }//GEN-LAST:event_cbReportesItemStateChanged

    private void cbHerramientasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbHerramientasItemStateChanged
       boolean seleccion = evt.getStateChange() == ItemEvent.SELECTED;
       this.activarPrivilegios(this.pnlHerramientas, seleccion);
       nuevoUsuario.setHerramientas(seleccion);
       nuevoUsuario.setCalculadora(seleccion);
       nuevoUsuario.setRespladarBd(seleccion);
       nuevoUsuario.setRestaurarBd(seleccion);
    }//GEN-LAST:event_cbHerramientasItemStateChanged

    private void cbAyudaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAyudaItemStateChanged
       boolean seleccion = evt.getStateChange() == ItemEvent.SELECTED;
       this.activarPrivilegios(this.pnlAyuda, seleccion);
       nuevoUsuario.setAyuda(seleccion);
       nuevoUsuario.setAcercade(seleccion);
    }//GEN-LAST:event_cbAyudaItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       getOptionPane();
       op.setValue(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        reiniciarCampos();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void cbIniciarSesionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIniciarSesionItemStateChanged
        nuevoUsuario.setIniciarSesion(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbIniciarSesionItemStateChanged

    private void cbCerrarSesionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCerrarSesionItemStateChanged
        nuevoUsuario.setCerrarSesion(evt.getStateChange() == ItemEvent.SELECTED);
        
    }//GEN-LAST:event_cbCerrarSesionItemStateChanged

    private void cbRegistroUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRegistroUsuariosItemStateChanged
        nuevoUsuario.setRegistroDeUsuario(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbRegistroUsuariosItemStateChanged

    private void cbSalirAplicacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSalirAplicacionItemStateChanged
        nuevoUsuario.setSalirDeAplicacion(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbSalirAplicacionItemStateChanged

    private void cbRegistroClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRegistroClientesItemStateChanged
       nuevoUsuario.setRegistroDeClientes(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbRegistroClientesItemStateChanged

    private void cbRegistroPagosPorClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRegistroPagosPorClientesItemStateChanged
        nuevoUsuario.setRegistrosDePagos(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbRegistroPagosPorClientesItemStateChanged

    private void cbEmisionDeOrdenesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEmisionDeOrdenesItemStateChanged
        nuevoUsuario.setEmisionesDeOrdenes(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbEmisionDeOrdenesItemStateChanged

    private void cbReporteIngresosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbReporteIngresosItemStateChanged
       nuevoUsuario.setReporteDeIngresos(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbReporteIngresosItemStateChanged

    private void cbReportePagosClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbReportePagosClientesItemStateChanged
        nuevoUsuario.setRegistrosDePagos(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbReportePagosClientesItemStateChanged

    private void cbReporteOrdenesEnviadasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbReporteOrdenesEnviadasItemStateChanged
        nuevoUsuario.setReporteDeOrdenes(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbReporteOrdenesEnviadasItemStateChanged

    private void cbCalculadoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCalculadoraItemStateChanged
       nuevoUsuario.setCalculadora(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbCalculadoraItemStateChanged

    private void cbRespaldarBdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRespaldarBdItemStateChanged
       nuevoUsuario.setRespladarBd(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbRespaldarBdItemStateChanged

    private void cbRestaurarBdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRestaurarBdItemStateChanged
        nuevoUsuario.setRestaurarBd(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbRestaurarBdItemStateChanged

    private void cbActivarAyudaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbActivarAyudaItemStateChanged
        nuevoUsuario.setAyuda(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbActivarAyudaItemStateChanged

    private void cbAcercaDeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAcercaDeItemStateChanged
       nuevoUsuario.setAcercade(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_cbAcercaDeItemStateChanged

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        String pass = String.valueOf(this.txtPassword.getPassword());
        if(this.txtUsuario.getText().isEmpty() || pass.isEmpty())
        {
            JOptionPane.showInternalMessageDialog(this, "Debe ingresar un nombre de usuario \n"
                    + "y una Contraseña", "Datos Obligatorios", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int procesoCorrecto = 0;
     nuevoUsuario.setUsuario(this.txtUsuario.getText());
     nuevoUsuario.setPasswd(pass);
        if(this.esUsuarioNuevo)
        {
            procesoCorrecto = nuevoUsuario.grabar();
            
        }else{
           procesoCorrecto = nuevoUsuario.actualizar();
        }
        
        if(procesoCorrecto != 0 && this.esUsuarioNuevo)
        { 
            this.procesoOk = true;
            int confirmacion = JOptionPane.showConfirmDialog(null, "Datos Guardado Correctamente.\n"
                    + "¿Desea Agregar otro usuario?",  "¿Desea continuar?",  JOptionPane.YES_NO_CANCEL_OPTION);
            if(confirmacion == JOptionPane.OK_OPTION)
            {
                reiniciarCampos();               
            }else
            {
                getOptionPane();
                op.setValue(1);
            }
            
        }else if(procesoCorrecto != 0 && !this.esUsuarioNuevo){
            this.procesoOk = true;
            JOptionPane.showInternalMessageDialog(this, "Usuario Actualizdo Correctamente"
                    , "Actualizacion Correcta.", JOptionPane.INFORMATION_MESSAGE); 
//             getOptionPane();
//             op.setValue(1);
        }else{
            JOptionPane.showInternalMessageDialog(this, "No fue posible Guardar los datos."
                    , "Error!!", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_bntGuardarActionPerformed

    private void getOptionPane()
    {
        if(op != null)
        {
            return;
        }
        Component pdr =this.getParent(); 
        while(pdr.getParent() != null)
        {
            if(pdr instanceof JOptionPane)
            {
                op = (JOptionPane)pdr;
                break;
            }            
            pdr = pdr.getParent();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JCheckBox cbAcercaDe;
    private javax.swing.JCheckBox cbActivarAyuda;
    private javax.swing.JCheckBox cbArchivo;
    private javax.swing.JCheckBox cbAyuda;
    private javax.swing.JCheckBox cbCalculadora;
    private javax.swing.JCheckBox cbCerrarSesion;
    private javax.swing.JCheckBox cbClientes;
    private javax.swing.JCheckBox cbEmisionDeOrdenes;
    private javax.swing.JCheckBox cbHerramientas;
    private javax.swing.JCheckBox cbIniciarSesion;
    private javax.swing.JCheckBox cbPagos;
    private javax.swing.JCheckBox cbRegistroClientes;
    private javax.swing.JCheckBox cbRegistroPagosPorClientes;
    private javax.swing.JCheckBox cbRegistroUsuarios;
    private javax.swing.JCheckBox cbReporteIngresos;
    private javax.swing.JCheckBox cbReporteOrdenesEnviadas;
    private javax.swing.JCheckBox cbReportePagosClientes;
    private javax.swing.JCheckBox cbReportes;
    private javax.swing.JCheckBox cbRespaldarBd;
    private javax.swing.JCheckBox cbRestaurarBd;
    private javax.swing.JCheckBox cbSalirAplicacion;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lbShow;
    private javax.swing.JPanel pnlArchivo;
    private javax.swing.JPanel pnlAyuda;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlHerramientas;
    private javax.swing.JPanel pnlPagos;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
